set(_CATKIN_CURRENT_PACKAGE "smclib")
set(smclib_VERSION "1.7.19")
set(smclib_MAINTAINER "Mikael Arguedas <mikael@osrfoundation.org>")
set(smclib_PACKAGE_FORMAT "2")
set(smclib_BUILD_DEPENDS )
set(smclib_BUILD_EXPORT_DEPENDS )
set(smclib_BUILDTOOL_DEPENDS "catkin")
set(smclib_BUILDTOOL_EXPORT_DEPENDS )
set(smclib_EXEC_DEPENDS )
set(smclib_RUN_DEPENDS )
set(smclib_TEST_DEPENDS )
set(smclib_DOC_DEPENDS )
set(smclib_DEPRECATED "")