# CMake generated Testfile for 
# Source directory: /home/pi/ros_catkin_ws/src/diagnostic_updater/self_test
# Build directory: /home/pi/ros_catkin_ws/build_isolated/self_test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_self_test_rostest_test_launch_nominal_test.launch "/home/pi/ros_catkin_ws/build_isolated/self_test/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/pi/ros_catkin_ws/build_isolated/self_test/test_results/self_test/rostest-test_launch_nominal_test.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/pi/ros_catkin_ws/src/diagnostic_updater/self_test --package=self_test --results-filename test_launch_nominal_test.xml --results-base-dir \"/home/pi/ros_catkin_ws/build_isolated/self_test/test_results\" /home/pi/ros_catkin_ws/src/diagnostic_updater/self_test/test/launch/nominal_test.launch ")
add_test(_ctest_self_test_rostest_test_launch_no_id_test.launch "/home/pi/ros_catkin_ws/build_isolated/self_test/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/pi/ros_catkin_ws/build_isolated/self_test/test_results/self_test/rostest-test_launch_no_id_test.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/pi/ros_catkin_ws/src/diagnostic_updater/self_test --package=self_test --results-filename test_launch_no_id_test.xml --results-base-dir \"/home/pi/ros_catkin_ws/build_isolated/self_test/test_results\" /home/pi/ros_catkin_ws/src/diagnostic_updater/self_test/test/launch/no_id_test.launch ")
add_test(_ctest_self_test_rostest_test_launch_error_test.launch "/home/pi/ros_catkin_ws/build_isolated/self_test/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/pi/ros_catkin_ws/build_isolated/self_test/test_results/self_test/rostest-test_launch_error_test.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/pi/ros_catkin_ws/src/diagnostic_updater/self_test --package=self_test --results-filename test_launch_error_test.xml --results-base-dir \"/home/pi/ros_catkin_ws/build_isolated/self_test/test_results\" /home/pi/ros_catkin_ws/src/diagnostic_updater/self_test/test/launch/error_test.launch ")
add_test(_ctest_self_test_rostest_test_launch_exception_test.launch "/home/pi/ros_catkin_ws/build_isolated/self_test/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/pi/ros_catkin_ws/build_isolated/self_test/test_results/self_test/rostest-test_launch_exception_test.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/pi/ros_catkin_ws/src/diagnostic_updater/self_test --package=self_test --results-filename test_launch_exception_test.xml --results-base-dir \"/home/pi/ros_catkin_ws/build_isolated/self_test/test_results\" /home/pi/ros_catkin_ws/src/diagnostic_updater/self_test/test/launch/exception_test.launch ")
subdirs(gtest)
subdirs(test)
