set(_CATKIN_CURRENT_PACKAGE "test_bond")
set(test_bond_VERSION "1.7.19")
set(test_bond_MAINTAINER "Mikael Arguedas <mikael@osrfoundation.org>")
set(test_bond_PACKAGE_FORMAT "2")
set(test_bond_BUILD_DEPENDS "bondcpp" "genmsg" "rostest")
set(test_bond_BUILD_EXPORT_DEPENDS )
set(test_bond_BUILDTOOL_DEPENDS "catkin")
set(test_bond_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")
set(test_bond_BUILDTOOL_EXPORT_DEPENDS )
set(test_bond_EXEC_DEPENDS )
set(test_bond_RUN_DEPENDS )
set(test_bond_TEST_DEPENDS "bondpy")
set(test_bond_DOC_DEPENDS )
set(test_bond_DEPRECATED "")