// Generated by gencpp from file vectornav/rawmeas.msg
// DO NOT EDIT!


#ifndef VECTORNAV_MESSAGE_RAWMEAS_H
#define VECTORNAV_MESSAGE_RAWMEAS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <vectornav/satraw.h>

namespace vectornav
{
template <class ContainerAllocator>
struct rawmeas_
{
  typedef rawmeas_<ContainerAllocator> Type;

  rawmeas_()
    : header()
    , tow(0.0)
    , week(0)
    , numSats(0)
    , resv(0)
    , satraws()  {
    }
  rawmeas_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , tow(0.0)
    , week(0)
    , numSats(0)
    , resv(0)
    , satraws(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _tow_type;
  _tow_type tow;

   typedef uint16_t _week_type;
  _week_type week;

   typedef uint8_t _numSats_type;
  _numSats_type numSats;

   typedef uint8_t _resv_type;
  _resv_type resv;

   typedef std::vector< ::vectornav::satraw_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::vectornav::satraw_<ContainerAllocator> >::other >  _satraws_type;
  _satraws_type satraws;




  typedef boost::shared_ptr< ::vectornav::rawmeas_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vectornav::rawmeas_<ContainerAllocator> const> ConstPtr;

}; // struct rawmeas_

typedef ::vectornav::rawmeas_<std::allocator<void> > rawmeas;

typedef boost::shared_ptr< ::vectornav::rawmeas > rawmeasPtr;
typedef boost::shared_ptr< ::vectornav::rawmeas const> rawmeasConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vectornav::rawmeas_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vectornav::rawmeas_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vectornav

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'vectornav': ['/home/pi/catkin_ws/src/vectornav/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vectornav::rawmeas_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vectornav::rawmeas_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vectornav::rawmeas_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vectornav::rawmeas_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vectornav::rawmeas_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vectornav::rawmeas_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vectornav::rawmeas_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea95944c129482cc512d818090e6d878";
  }

  static const char* value(const ::vectornav::rawmeas_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea95944c129482ccULL;
  static const uint64_t static_value2 = 0x512d818090e6d878ULL;
};

template<class ContainerAllocator>
struct DataType< ::vectornav::rawmeas_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vectornav/rawmeas";
  }

  static const char* value(const ::vectornav::rawmeas_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vectornav::rawmeas_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header       header\n\
float64               tow\n\
uint16                week\n\
uint8                 numSats\n\
uint8                 resv\n\
satraw[]              satraws\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: vectornav/satraw\n\
uint8                sys\n\
uint8                svId\n\
uint8                freq\n\
uint8                chan\n\
int8                 slot\n\
uint8                cno\n\
uint16               flags\n\
float64              pr\n\
float64              cp\n\
float32              dp\n\
";
  }

  static const char* value(const ::vectornav::rawmeas_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vectornav::rawmeas_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.tow);
      stream.next(m.week);
      stream.next(m.numSats);
      stream.next(m.resv);
      stream.next(m.satraws);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rawmeas_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vectornav::rawmeas_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vectornav::rawmeas_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "tow: ";
    Printer<double>::stream(s, indent + "  ", v.tow);
    s << indent << "week: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.week);
    s << indent << "numSats: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.numSats);
    s << indent << "resv: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.resv);
    s << indent << "satraws[]" << std::endl;
    for (size_t i = 0; i < v.satraws.size(); ++i)
    {
      s << indent << "  satraws[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::vectornav::satraw_<ContainerAllocator> >::stream(s, indent + "    ", v.satraws[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VECTORNAV_MESSAGE_RAWMEAS_H
