set(_CATKIN_CURRENT_PACKAGE "bondcpp")
set(bondcpp_VERSION "1.7.19")
set(bondcpp_MAINTAINER "Mikael Arguedas <mikael@osrfoundation.org>")
set(bondcpp_PACKAGE_FORMAT "2")
set(bondcpp_BUILD_DEPENDS "cmake_modules" "bond" "boost" "roscpp" "smclib" "uuid")
set(bondcpp_BUILD_DEPENDS_cmake_modules_VERSION_GTE "0.3.2")
set(bondcpp_BUILD_EXPORT_DEPENDS "bond" "boost" "roscpp" "smclib" "uuid")
set(bondcpp_BUILDTOOL_DEPENDS "catkin")
set(bondcpp_BUILDTOOL_EXPORT_DEPENDS )
set(bondcpp_EXEC_DEPENDS "bond" "boost" "roscpp" "smclib" "uuid")
set(bondcpp_RUN_DEPENDS "bond" "boost" "roscpp" "smclib" "uuid")
set(bondcpp_TEST_DEPENDS )
set(bondcpp_DOC_DEPENDS )
set(bondcpp_DEPRECATED "")