# CMake generated Testfile for 
# Source directory: /home/pi/ros_catkin_ws/src/tf2/tf2_geometry_msgs
# Build directory: /home/pi/ros_catkin_ws/build_isolated/tf2_geometry_msgs
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_tf2_geometry_msgs_gtest_test_tomsg_frommsg "/home/pi/ros_catkin_ws/build_isolated/tf2_geometry_msgs/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/pi/ros_catkin_ws/build_isolated/tf2_geometry_msgs/test_results/tf2_geometry_msgs/gtest-test_tomsg_frommsg.xml" "--return-code" "/home/pi/ros_catkin_ws/devel_isolated/tf2_geometry_msgs/lib/tf2_geometry_msgs/test_tomsg_frommsg --gtest_output=xml:/home/pi/ros_catkin_ws/build_isolated/tf2_geometry_msgs/test_results/tf2_geometry_msgs/gtest-test_tomsg_frommsg.xml")
add_test(_ctest_tf2_geometry_msgs_rostest_test_test.launch "/home/pi/ros_catkin_ws/build_isolated/tf2_geometry_msgs/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/pi/ros_catkin_ws/build_isolated/tf2_geometry_msgs/test_results/tf2_geometry_msgs/rostest-test_test.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/pi/ros_catkin_ws/src/tf2/tf2_geometry_msgs --package=tf2_geometry_msgs --results-filename test_test.xml --results-base-dir \"/home/pi/ros_catkin_ws/build_isolated/tf2_geometry_msgs/test_results\" /home/pi/ros_catkin_ws/src/tf2/tf2_geometry_msgs/test/test.launch ")
add_test(_ctest_tf2_geometry_msgs_rostest_test_test_python.launch "/home/pi/ros_catkin_ws/build_isolated/tf2_geometry_msgs/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/pi/ros_catkin_ws/build_isolated/tf2_geometry_msgs/test_results/tf2_geometry_msgs/rostest-test_test_python.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/pi/ros_catkin_ws/src/tf2/tf2_geometry_msgs --package=tf2_geometry_msgs --results-filename test_test_python.xml --results-base-dir \"/home/pi/ros_catkin_ws/build_isolated/tf2_geometry_msgs/test_results\" /home/pi/ros_catkin_ws/src/tf2/tf2_geometry_msgs/test/test_python.launch ")
subdirs(gtest)
