set(_CATKIN_CURRENT_PACKAGE "actionlib")
set(actionlib_VERSION "1.11.10")
set(actionlib_MAINTAINER "Mikael Arguedas <mikael@osrfoundation.org>")
set(actionlib_PACKAGE_FORMAT "2")
set(actionlib_BUILD_DEPENDS "message_generation" "actionlib_msgs" "boost" "roscpp" "rospy" "rostest" "std_msgs")
set(actionlib_BUILD_EXPORT_DEPENDS "actionlib_msgs" "boost" "roscpp" "rospy" "rostest" "std_msgs")
set(actionlib_BUILDTOOL_DEPENDS "catkin")
set(actionlib_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.78")
set(actionlib_BUILDTOOL_EXPORT_DEPENDS )
set(actionlib_EXEC_DEPENDS "message_runtime" "python-wxtools" "roslib" "rostopic" "actionlib_msgs" "boost" "roscpp" "rospy" "rostest" "std_msgs")
set(actionlib_RUN_DEPENDS "message_runtime" "python-wxtools" "roslib" "rostopic" "actionlib_msgs" "boost" "roscpp" "rospy" "rostest" "std_msgs")
set(actionlib_TEST_DEPENDS "rosnode")
set(actionlib_DOC_DEPENDS )
set(actionlib_DEPRECATED "")