# CMake generated Testfile for 
# Source directory: /home/pi/ros_catkin_ws/src/diagnostic_updater/diagnostic_aggregator
# Build directory: /home/pi/ros_catkin_ws/build_isolated/diagnostic_aggregator
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_diagnostic_aggregator_rostest_test_launch_test_agg.launch "/home/pi/ros_catkin_ws/build_isolated/diagnostic_aggregator/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/pi/ros_catkin_ws/build_isolated/diagnostic_aggregator/test_results/diagnostic_aggregator/rostest-test_launch_test_agg.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/pi/ros_catkin_ws/src/diagnostic_updater/diagnostic_aggregator --package=diagnostic_aggregator --results-filename test_launch_test_agg.xml --results-base-dir \"/home/pi/ros_catkin_ws/build_isolated/diagnostic_aggregator/test_results\" /home/pi/ros_catkin_ws/src/diagnostic_updater/diagnostic_aggregator/test/launch/test_agg.launch ")
add_test(_ctest_diagnostic_aggregator_rostest_test_launch_test_add_agg.launch "/home/pi/ros_catkin_ws/build_isolated/diagnostic_aggregator/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/pi/ros_catkin_ws/build_isolated/diagnostic_aggregator/test_results/diagnostic_aggregator/rostest-test_launch_test_add_agg.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/pi/ros_catkin_ws/src/diagnostic_updater/diagnostic_aggregator --package=diagnostic_aggregator --results-filename test_launch_test_add_agg.xml --results-base-dir \"/home/pi/ros_catkin_ws/build_isolated/diagnostic_aggregator/test_results\" /home/pi/ros_catkin_ws/src/diagnostic_updater/diagnostic_aggregator/test/launch/test_add_agg.launch ")
add_test(_ctest_diagnostic_aggregator_rostest_test_launch_test_loader.launch "/home/pi/ros_catkin_ws/build_isolated/diagnostic_aggregator/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/pi/ros_catkin_ws/build_isolated/diagnostic_aggregator/test_results/diagnostic_aggregator/rostest-test_launch_test_loader.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/pi/ros_catkin_ws/src/diagnostic_updater/diagnostic_aggregator --package=diagnostic_aggregator --results-filename test_launch_test_loader.xml --results-base-dir \"/home/pi/ros_catkin_ws/build_isolated/diagnostic_aggregator/test_results\" /home/pi/ros_catkin_ws/src/diagnostic_updater/diagnostic_aggregator/test/launch/test_loader.launch ")
add_test(_ctest_diagnostic_aggregator_rostest_test_launch_test_expected_stale.launch "/home/pi/ros_catkin_ws/build_isolated/diagnostic_aggregator/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/pi/ros_catkin_ws/build_isolated/diagnostic_aggregator/test_results/diagnostic_aggregator/rostest-test_launch_test_expected_stale.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/pi/ros_catkin_ws/src/diagnostic_updater/diagnostic_aggregator --package=diagnostic_aggregator --results-filename test_launch_test_expected_stale.xml --results-base-dir \"/home/pi/ros_catkin_ws/build_isolated/diagnostic_aggregator/test_results\" /home/pi/ros_catkin_ws/src/diagnostic_updater/diagnostic_aggregator/test/launch/test_expected_stale.launch ")
add_test(_ctest_diagnostic_aggregator_rostest_test_launch_test_multiple_match.launch "/home/pi/ros_catkin_ws/build_isolated/diagnostic_aggregator/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/pi/ros_catkin_ws/build_isolated/diagnostic_aggregator/test_results/diagnostic_aggregator/rostest-test_launch_test_multiple_match.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/pi/ros_catkin_ws/src/diagnostic_updater/diagnostic_aggregator --package=diagnostic_aggregator --results-filename test_launch_test_multiple_match.xml --results-base-dir \"/home/pi/ros_catkin_ws/build_isolated/diagnostic_aggregator/test_results\" /home/pi/ros_catkin_ws/src/diagnostic_updater/diagnostic_aggregator/test/launch/test_multiple_match.launch ")
subdirs(gtest)
